services:
    _defaults:
        autowire: true
        autoconfigure: true

    Skrip42\Bundle\CronBundle\Repository\ScheduleRepository:
        class: Skrip42\Bundle\CronBundle\Repository\ScheduleRepository
        tags:
            - { name: doctrine.repository_service }

    Skrip42\Bundle\CronBundle\Services\Cron:
        class: Skrip42\Bundle\CronBundle\Services\Cron

    Skrip42\Bundle\CronBundle\Command\CronRunCommand:
        class: Skrip42\Bundle\CronBundle\Command\CronRunCommand
        tags:
            - { name: console.command }
    Skrip42\Bundle\CronBundle\Command\CronAddCommand:
        class: Skrip42\Bundle\CronBundle\Command\CronAddCommand
        tags:
            - { name: console.command }
    Skrip42\Bundle\CronBundle\Command\CronListCommand:
        class: Skrip42\Bundle\CronBundle\Command\CronListCommand
        tags:
            - { name: console.command }
    Skrip42\Bundle\CronBundle\Command\CronOptimizeCommand:
        class: Skrip42\Bundle\CronBundle\Command\CronOptimizeCommand
        tags:
            - { name: console.command }
    Skrip42\Bundle\CronBundle\Command\CronClosestCommand:
        class: Skrip42\Bundle\CronBundle\Command\CronClosestCommand
        tags:
            - { name: console.command }
    Skrip42\Bundle\CronBundle\Command\CronUpdateCommand:
        class: Skrip42\Bundle\CronBundle\Command\CronUpdateCommand
        tags:
            - { name: console.command }
    Skrip42\Bundle\CronBundle\Command\CronToggleCommand:
        class: Skrip42\Bundle\CronBundle\Command\CronToggleCommand
        tags:
            - { name: console.command }
